package biblioteca;
// Generated 10-ene-2020 16:42:18 by Hibernate Tools 5.4.7.Final

/**
 * Autor generated by hbm2java
 */
public class Autor implements java.io.Serializable {

	private Integer idAutor;
	private String nomAutor;

	public Autor() {
	}

	public Autor(String nomAutor) {
		this.nomAutor = nomAutor;
	}

	public Integer getIdAutor() {
		return this.idAutor;
	}

	private void setIdAutor(Integer idAutor) {
		this.idAutor = idAutor;
	}

	public String getNomAutor() {
		return this.nomAutor;
	}

	public void setNomAutor(String nomAutor) {
		this.nomAutor = nomAutor;
	}

}
