package biblioteca;
// Generated 10-ene-2020 16:42:18 by Hibernate Tools 5.4.7.Final

/**
 * Llibres generated by hbm2java
 */
public class Llibres implements java.io.Serializable {

	private Integer idLlibre;
	private String nomLlibre;
	private String editoria;

	public Llibres() {
	}

	public Llibres(String nomLlibre) {
		this.nomLlibre = nomLlibre;
	}

	public Llibres(String nomLlibre, String editoria) {
		this.nomLlibre = nomLlibre;
		this.editoria = editoria;
	}

	public Integer getIdLlibre() {
		return this.idLlibre;
	}

	private void setIdLlibre(Integer idLlibre) {
		this.idLlibre = idLlibre;
	}

	public String getNomLlibre() {
		return this.nomLlibre;
	}

	public void setNomLlibre(String nomLlibre) {
		this.nomLlibre = nomLlibre;
	}

	public String getEditoria() {
		return this.editoria;
	}

	public void setEditoria(String editoria) {
		this.editoria = editoria;
	}

}
